import { PrismaClient } from "@prisma/client";
import slugify from "slugify";

const prisma = new PrismaClient();

function slug(titulo: string) {
  return slugify(titulo, { lower: true, strict: true, locale: "es" }) + "-" + Date.now().toString(36);
}
function codigo() {
  return `MZA-${String(Math.floor(Math.random() * 90000) + 10000)}`;
}

async function main() {
  const admin = await prisma.usuario.findUnique({ where: { email: "admin@inmobiliaria.com" } });
  if (!admin) throw new Error("Corré primero el seed principal");

  const barrioChacras   = await prisma.barrio.findFirst({ where: { nombre: "Chacras de Coria" } });
  const barrioVistalba  = await prisma.barrio.findFirst({ where: { nombre: "Vistalba" } });
  const barrioGodoy     = await prisma.barrio.findFirst({ where: { nombre: "Bombal" } });
  const barrioCentro    = await prisma.barrio.findFirst({ where: { nombre: "Centro" } });
  const barrioGuaym     = await prisma.barrio.findFirst({ where: { nombre: "Dorrego" } });
  const barrioMaipu     = await prisma.barrio.findFirst({ where: { nombre: "Luzuriaga" } });

  const amenityPileta   = await prisma.amenity.findFirst({ where: { nombre: "Pileta" } });
  const amenityParrilla = await prisma.amenity.findFirst({ where: { nombre: "Parrilla" } });
  const amenityCordillera = await prisma.amenity.findFirst({ where: { nombre: "Vista a la Cordillera" } });
  const amenityJardin   = await prisma.amenity.findFirst({ where: { nombre: "Jardín" } });
  const amenitySeguridad = await prisma.amenity.findFirst({ where: { nombre: "Seguridad 24hs" } });

  const propiedades = [
    {
      codigo: codigo(),
      titulo: "Casa con pileta y jardín en Chacras de Coria",
      descripcion: "Espectacular casa de categoría ubicada en el corazón de Chacras de Coria. Cuenta con 3 dormitorios en suite, amplio living comedor con chimenea, cocina equipada, pileta de natación y jardín con parrilla. Excelente iluminación natural y vistas a la cordillera. Barrio privado con seguridad 24hs.",
      tipoOperacion: "VENTA" as const,
      tipoPropiedad: "CASA" as const,
      estadoConstruccion: "USADO" as const,
      estado: "DISPONIBLE" as const,
      precio: 380000,
      moneda: "USD" as const,
      precioNegociable: true,
      superficieTotal: 800,
      superficieCubierta: 280,
      dormitorios: 3,
      banos: 3,
      cocheras: 2,
      antiguedad: 8,
      direccion: "Los Álamos 1200, Chacras de Coria",
      barrioId: barrioChacras?.id,
      latitud: -33.0150,
      longitud: -68.8620,
      mostrarDireccionExacta: false,
      destacada: true,
      agenteId: admin.id,
      slug: slug("Casa con pileta y jardín en Chacras de Coria"),
      publicadaEn: new Date(),
      amenities: [amenityPileta?.id, amenityParrilla?.id, amenityCordillera?.id, amenityJardin?.id, amenitySeguridad?.id].filter(Boolean) as number[],
    },
    {
      codigo: codigo(),
      titulo: "Departamento a estrenar con vista a la Cordillera",
      descripcion: "Moderno departamento de 2 dormitorios a estrenar en el mejor punto de Godoy Cruz. Piso 8 con vista despejada hacia la Cordillera de los Andes. Terminaciones de primera calidad, cocina integrada al living, balcón amplio. Edificio con amenities: gimnasio y SUM.",
      tipoOperacion: "VENTA" as const,
      tipoPropiedad: "DEPARTAMENTO" as const,
      estadoConstruccion: "A_ESTRENAR" as const,
      estado: "DISPONIBLE" as const,
      precio: 145000,
      moneda: "USD" as const,
      precioNegociable: false,
      superficieTotal: 72,
      superficieCubierta: 68,
      dormitorios: 2,
      banos: 1,
      cocheras: 1,
      antiguedad: 0,
      direccion: "Av. San Martín 4500, Godoy Cruz",
      barrioId: barrioGodoy?.id,
      latitud: -32.9250,
      longitud: -68.8450,
      mostrarDireccionExacta: false,
      destacada: true,
      agenteId: admin.id,
      slug: slug("Departamento a estrenar con vista a la Cordillera"),
      publicadaEn: new Date(),
      amenities: [amenityCordillera?.id].filter(Boolean) as number[],
    },
    {
      codigo: codigo(),
      titulo: "Terreno en Vistalba ideal para construcción",
      descripcion: "Terreno de 1000 m² en zona residencial de Vistalba, Luján de Cuyo. Excelente ubicación a pocas cuadras de bodegas de renombre. Todos los servicios disponibles. Escritura al día. Ideal para construcción de casa de categoría o proyecto de inversión.",
      tipoOperacion: "VENTA" as const,
      tipoPropiedad: "TERRENO" as const,
      estadoConstruccion: "USADO" as const,
      estado: "DISPONIBLE" as const,
      precio: 95000,
      moneda: "USD" as const,
      precioNegociable: true,
      superficieTotal: 1000,
      superficieCubierta: null,
      dormitorios: null,
      banos: null,
      cocheras: 0,
      antiguedad: null,
      direccion: "Calle Cobos 500, Vistalba",
      barrioId: barrioVistalba?.id,
      latitud: -33.0480,
      longitud: -68.9050,
      mostrarDireccionExacta: false,
      destacada: false,
      agenteId: admin.id,
      slug: slug("Terreno en Vistalba ideal para construcción"),
      publicadaEn: new Date(),
      amenities: [],
    },
    {
      codigo: codigo(),
      titulo: "Departamento 1 dormitorio en alquiler — Centro Mendoza",
      descripcion: "Luminoso departamento de 1 dormitorio en pleno centro de la Ciudad de Mendoza. A pasos del Parque General San Martín. Piso 3, excelente estado. Incluye: aire acondicionado frío/calor, calefacción central, cocina equipada. Expensas incluidas en el precio.",
      tipoOperacion: "ALQUILER" as const,
      tipoPropiedad: "DEPARTAMENTO" as const,
      estadoConstruccion: "USADO" as const,
      estado: "DISPONIBLE" as const,
      precio: 350000,
      moneda: "ARS" as const,
      precioNegociable: false,
      superficieTotal: 45,
      superficieCubierta: 42,
      dormitorios: 1,
      banos: 1,
      cocheras: 0,
      antiguedad: 15,
      direccion: "Av. Colón 800, Capital",
      barrioId: barrioCentro?.id,
      latitud: -32.8908,
      longitud: -68.8272,
      mostrarDireccionExacta: false,
      destacada: false,
      agenteId: admin.id,
      slug: slug("Departamento 1 dormitorio en alquiler Centro Mendoza"),
      publicadaEn: new Date(),
      amenities: [],
    },
    {
      codigo: codigo(),
      titulo: "Casa 4 dormitorios en Dorrego — Guaymallén",
      descripcion: "Amplia casa familiar en Dorrego con 4 dormitorios, 2 baños completos y toilette. Gran patio trasero con parrilla y espacio para pileta. Garaje doble. A 10 minutos del centro de Mendoza. Ideal para familia numerosa. Barrio tranquilo con buena conexión de transporte.",
      tipoOperacion: "VENTA" as const,
      tipoPropiedad: "CASA" as const,
      estadoConstruccion: "USADO" as const,
      estado: "DISPONIBLE" as const,
      precio: 195000,
      moneda: "USD" as const,
      precioNegociable: true,
      superficieTotal: 400,
      superficieCubierta: 210,
      dormitorios: 4,
      banos: 3,
      cocheras: 2,
      antiguedad: 20,
      direccion: "Calle Tucumán 3200, Dorrego",
      barrioId: barrioGuaym?.id,
      latitud: -32.9120,
      longitud: -68.7980,
      mostrarDireccionExacta: false,
      destacada: true,
      agenteId: admin.id,
      slug: slug("Casa 4 dormitorios en Dorrego Guaymallén"),
      publicadaEn: new Date(),
      amenities: [amenityParrilla?.id, amenityJardin?.id].filter(Boolean) as number[],
    },
    {
      codigo: codigo(),
      titulo: "Casa en alquiler temporario — Luján de Cuyo",
      descripcion: "Hermosa casa de campo disponible para alquiler temporario en Luján de Cuyo, rodeada de viñedos. 2 dormitorios, pileta, parrilla y vistas espectaculares a la Cordillera. WiFi, ropa de cama incluida. Mínimo 3 noches. Perfecta para una escapada de fin de semana o turismo bodeguero.",
      tipoOperacion: "ALQUILER_TEMPORARIO" as const,
      tipoPropiedad: "CASA" as const,
      estadoConstruccion: "USADO" as const,
      estado: "DISPONIBLE" as const,
      precio: 80000,
      moneda: "ARS" as const,
      precioNegociable: false,
      superficieTotal: 350,
      superficieCubierta: 120,
      dormitorios: 2,
      banos: 2,
      cocheras: 1,
      antiguedad: 5,
      direccion: "Ruta Provincial 15, Luján de Cuyo",
      barrioId: barrioVistalba?.id,
      latitud: -33.0300,
      longitud: -68.9200,
      mostrarDireccionExacta: false,
      destacada: false,
      agenteId: admin.id,
      slug: slug("Casa en alquiler temporario Luján de Cuyo"),
      publicadaEn: new Date(),
      amenities: [amenityPileta?.id, amenityParrilla?.id, amenityCordillera?.id].filter(Boolean) as number[],
    },
    {
      codigo: codigo(),
      titulo: "Departamento en alquiler 2 dorm — Maipú",
      descripcion: "Cómodo departamento en planta baja con jardín privado en Luzuriaga, Maipú. 2 dormitorios, 1 baño, cocina completa, lavadero. Jardín de uso exclusivo 30m². Estacionamiento descubierto. Excelente estado de mantenimiento.",
      tipoOperacion: "ALQUILER" as const,
      tipoPropiedad: "DEPARTAMENTO" as const,
      estadoConstruccion: "USADO" as const,
      estado: "DISPONIBLE" as const,
      precio: 280000,
      moneda: "ARS" as const,
      precioNegociable: false,
      superficieTotal: 70,
      superficieCubierta: 65,
      dormitorios: 2,
      banos: 1,
      cocheras: 1,
      antiguedad: 10,
      direccion: "Calle Ozamis 500, Luzuriaga",
      barrioId: barrioMaipu?.id,
      latitud: -32.9870,
      longitud: -68.7830,
      mostrarDireccionExacta: false,
      destacada: false,
      agenteId: admin.id,
      slug: slug("Departamento en alquiler 2 dorm Maipú"),
      publicadaEn: new Date(),
      amenities: [amenityJardin?.id].filter(Boolean) as number[],
    },
    {
      codigo: codigo(),
      titulo: "Local comercial en venta — Zona céntrica Capital",
      descripcion: "Local comercial de 120m² en esquina, en una de las arterias comerciales más transitadas de la Ciudad de Mendoza. Actualmente en funcionamiento como local gastronómico. Apto para cualquier rubro. Excelente visibilidad, gran flujo peatonal.",
      tipoOperacion: "VENTA" as const,
      tipoPropiedad: "LOCAL_COMERCIAL" as const,
      estadoConstruccion: "USADO" as const,
      estado: "DISPONIBLE" as const,
      precio: 220000,
      moneda: "USD" as const,
      precioNegociable: true,
      superficieTotal: 120,
      superficieCubierta: 120,
      dormitorios: null,
      banos: 1,
      cocheras: 0,
      antiguedad: 30,
      direccion: "Av. Las Heras y Colon, Capital",
      barrioId: barrioCentro?.id,
      latitud: -32.8875,
      longitud: -68.8310,
      mostrarDireccionExacta: false,
      destacada: false,
      agenteId: admin.id,
      slug: slug("Local comercial en venta zona céntrica Capital"),
      publicadaEn: new Date(),
      amenities: [],
    },
  ];

  for (const { amenities, ...datos } of propiedades) {
    await prisma.propiedad.create({
      data: {
        ...datos,
        superficieTotal: datos.superficieTotal ?? undefined,
        superficieCubierta: datos.superficieCubierta ?? undefined,
        dormitorios: datos.dormitorios ?? undefined,
        banos: datos.banos ?? undefined,
        antiguedad: datos.antiguedad ?? undefined,
        barrioId: datos.barrioId ?? undefined,
        latitud: datos.latitud ?? undefined,
        longitud: datos.longitud ?? undefined,
        amenities: { create: amenities.map(id => ({ amenityId: id })) },
      },
    });
  }

  console.log(`✅ ${propiedades.length} propiedades de prueba cargadas.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
